version: '3'

services:
    postgres:
      container_name: postgres
      image: postgres:12-alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=fes6se
        - POSTGRES_DB=postgres
      volumes:
        - ../pgdata:/var/lib/postgresql/data:rw
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    redis:
      container_name: redis
      image: redis:6-alpine
      ports:
        - "6379:6379"
